### PR TITLE
Add commit --allow-empty-message option and fix empty message parsing in process_commit_log_data

### LINKED ISSUE #481: Incorrect log if repo contains commits with empty message
### Subject of the issue
If repository contains commit made by `git commit --allow-empty --allow-empty-message -m ""` log return incorrect commits history. Returned history starts from this commit with empty message.

### Your environment
```
$ git --version
git version 2.20.1
```
```
$ sudo gem install git     
Successfully installed git-1.7.0
```
```
$ ruby --version 
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
```

### Steps to reproduce
Create testing git repository:
```
mkdir test
cd test
git init
git commit -m "test" --allow-empty
git commit -m "test2" --allow-empty
git commit -m "" --allow-empty --allow-empty-message
git commit -m "test3" --allow-empty
```
Get real commit history:
```
$ git log | tee test
commit fc940fc8858011566d6a16076d01bcf189955b37
Author: ...
Date:   Mon Aug 10 17:34:10 2020 +0300

    test3

commit 58dc8ed01e328ea4cea39b28a01aa4500be5e385
Author: ...
Date:   Mon Aug 10 17:34:02 2020 +0300

commit 458f6e6b9305df15a9c23c3dffaf7448d917c72f
Author: ...
Date:   Mon Aug 10 17:33:43 2020 +0300

    test2

commit 9dd305fe98ef19385906e39cdb31ee7696f53e03
Author: ...
Date:   Mon Aug 10 17:33:37 2020 +0300

    test
```
Create test ruby script (named test.rb):
```ruby
require "git"

g = Git.open("~/test")

g.log.to_a.each do |com|
   puts com.sha 
end
```
Call it:
```
$ ruby test.rb                                                 
fc940fc8858011566d6a16076d01bcf189955b37
58dc8ed01e328ea4cea39b28a01aa4500be5e385
```
As we can see this is not all commit history.

### Expected behaviour
Retrieving complete commit history

### Actual behaviour
The commit history is truncated from a commit with an empty message

### PR DESCRIPTION
**Pull request by kpd200081**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/ruby-git/ruby-git/blob/master/CONTRIBUTING.md) to this repository.

- [x] Ensure all commits include DCO sign-off.
- [x] Ensure that your contributions pass unit testing.
- [x] Ensure that your contributions contain documentation if applicable.

### Description
If the commit doesn't contain a message, parsing the output of "git log"
results in an error, which occures because the end of the commit message
can't be detected.

fixes #481

### CODE REVIEW

**Comment by kpd200081** [comment]
@rvodden @perlun @tarcinil, please can somebody review this pull request?

PS: build passed https://travis-ci.org/github/ruby-git/ruby-git/builds/716900598, I'm not sure why the status is not updating

**Comment by jcouball** [comment]
I re-ran the build and the status was updated.  Not sure why it wasn't updating before.

**Comment by jcouball** [comment]
@kpd200081 can you please add a failing test that this change fixes?

You should probable create your own test fixture instead of changing existing fixtures. If you don't have time to figure this out, I can help out -- just let me know.  Here is what I told someone else:

> Reusing the default test fixture (test/files/working/dot_git) breaks tests that don't have anything to do with the change you are making. To me this is tech debt that is piling up with each change like this one. The next PR might have to correct all the same tests plus the new ones introduced in this PR. Additionally, I think merge conflicts will be more of a problem if everyone is trying to change the same test fixture for their tests.
> 
> You can see an example of using a different fixture in `tests/units/test_diff_non_default_encoding.rb` for using the fixture `tests/files/encoding`.  It would probably be good to create a new git working copy setup just for your test instead of copying an existing one that has a lot of setup for other things.

**Comment by kpd200081** [comment]
@jcouball, I'm not sure if a test is needed for this case. 

Anyway, I'm not familiar with Ruby tests, so if you think it's necessary it would be nice if you could help with that.

**Comment by kpd200081** [comment]
@jcouball I added a test that falling without this fix, but I had to change the `commit` method a bit, take a look please

As we can see in travis it fail because run on published version of gem (I don't know why, locally I have same behavior)

File: lib/git/lib.rb [hunk 1]
```diff
@@ -571,6 +574,7 @@ def commit(message, opts = {})
       arr_opts << "--author=#{opts[:author]}" if opts[:author]
       arr_opts << "--date=#{opts[:date]}" if opts[:date].is_a? String
       arr_opts << '--no-verify' if opts[:no_verify]
+      arr_opts |= opts[:raw_opts] if opts.key?(:raw_opts)
```
Comment (jcouball) [inline lib/git/lib.rb]: It seems like the convention (and I'm not giving an opinion if the convention is good or bad) is to add an option `:allow_empty_message` instead of passing in an array of "raw options" to allow for this option.

What do you think about sticking with that convention and changing this line to (this is my untested guess):

```Ruby
arr_opts << '--allow_empty_message' if opts[:allow_empty_message]
```

and then update the documentation accordingly.

Also, isn't the documentation for `opts` wrong?  Should it say that a Hash is expected instead of an Array?

File: tests/units/test_log_empty_message.rb [hunk 2]
```diff
@@ -0,0 +1,18 @@
+#!/usr/bin/env ruby
+require File.dirname(__FILE__) + '/../test_helper'
+
+class TestLogEmptyMessage < Test::Unit::TestCase
+  def setup
+    set_file_paths
+  end
+  
+  def test_repo_with_empty_commit
```
Comment (jcouball) [inline tests/units/test_log_empty_message.rb]: I think this test name should be changed to `test_repo_with_empty_commit_message` since empty commit is something different.

For this functionality, I would think to do two tests:
1. 
a test that does not have a commit message and does not use the `:allow_empty_message` option
2. a test that does not have a commit message and DOES use the `:allow_empty_messages` option

Since the `:allow_empty` and `:allow_empty_message` options are so similar, I found the use of the `:allow_empty` option in this particular test confusing. I'll leave it up to you if you want to do anything about this.

Comment (kpd200081) [reply tests/units/test_log_empty_message.rb]: >I think this test name should be changed to `test_repo_with_empty_commit_message` since empty commit is something different.

oh, year, I did misspell here

>Since the :allow_empty and :allow_empty_message options are so similar, I found the use of the :allow_empty option in this particular test confusing. I'll leave it up to you if you want to do anything about this.

`:allow_empty` just allow commit without changes, so it was added to both commits

File: lib/git/lib.rb (hunk 1 above)
Comment (kpd200081) [reply lib/git/lib.rb]: I think about it and decide that `:allow_empty_message` will be really rare used, at the other hand `:raw_opts` can be used for different purposes

>Also, isn't the documentation for opts wrong? Should it say that a Hash is expected instead of an Array?

Year, it definitely Hash, should we fix it in this Pull Request?

>It seems like the convention

It's not convention, just array appending

File: tests/units/test_log_empty_message.rb (hunk 2 above)
Comment (kpd200081) [reply tests/units/test_log_empty_message.rb]: >a test that does not have a commit message and does not use the `:allow_empty_message` option

we can't commit without this option, this results in an error in `git` and test failure

File: lib/git/lib.rb (hunk 1 above)
Comment (jcouball) [reply lib/git/lib.rb]: I believe we should change this to follow the convention of using specific hash keys for passing options (passing `:allow_empty_message` instead of `:raw_opts`)

One reason for this convention is to constrain how use this gem is used so users don't give combinations of options that this gem wouldn't respond well to. This is how the rest of the Git gem interface works. I don't see a reason to violate this convention just for this case. After all, isn't `:allow_empty` just as rarely used?  Why give two different ways for passing arguments?

**Comment by kpd200081** [comment]
@jcouball I apply suggestions to test name and `opts` type documentation, also I reply to other questions.

File: lib/git/lib.rb (hunk 1 above)
Comment (kpd200081) [reply lib/git/lib.rb]: Ok, you convinced me

File: tests/units/test_log_empty_message.rb (hunk 2 above)
Comment (kpd200081) [reply tests/units/test_log_empty_message.rb]: So, as test without `:allow_empty_message` can't work because of `git` internal error, can we resolve this?

**Comment by kpd200081** [comment]
@jcouball should I rebase it?

**Comment by kpd200081** [comment]
@jcouball I fix commit author and rebase to remove merge commit, now  I think nothing block from accepting PR.
